# This program takes in data for SemEval Task 3 subtask 1 tract A and produces a BIOES labeling scheme from given orthographic labels. BIOES tags are based on tokenizer. 

import requests
from transformers import AutoTokenizer
import json
from typing import List, Dict
import pandas as pd
import numpy as np
import torch
import ast
import re

# Definition of Gloabal Labels


# loads Task Data from organizer Github - Taken from starter Kit
def load_jsonl_url(url: str) -> List[Dict]:
    resp = requests.get(url)
    resp.raise_for_status()
    return [json.loads(line) for line in resp.text.splitlines()]

# Transforms data from JSON to Python-friendly DataFrame - Taken from starter Kit
def jsonl_to_df(data):
    if 'Quadruplet' in data[0]:
        df = pd.json_normalize(data, 'Quadruplet', ['ID', 'Text'])
        df[['Valence', 'Arousal']] = df['VA'].str.split('#', expand=True).astype(float)
        df = df.drop(columns=['VA', 'Category', 'Opinion'])  # drop unnecessary columns
        df = df.drop_duplicates(subset=['ID', 'Aspect'], keep='first')  # remove duplicate ID+Aspect

    elif 'Triplet' in data[0]:
        df = pd.json_normalize(data, 'Triplet', ['ID', 'Text'])
        df[['Valence', 'Arousal']] = df['VA'].str.split('#', expand=True).astype(float)
        df = df.drop(columns=['VA', 'Opinion'])  # drop unnecessary columns
        df = df.drop_duplicates(subset=['ID', 'Aspect'], keep='first')  # remove duplicate ID+Aspect

    elif 'Aspect' in data[0]:
        df = pd.json_normalize(data, 'Aspect', ['ID', 'Text'])
        df = df.rename(columns={df.columns[0]: "Aspect"})  # rename to Aspect
        df['Valence'] = 0  # default value
        df['Arousal'] = 0  # default value

    else:
        raise ValueError("Invalid format: must include 'Quadruplet' or 'Triplet' or 'Aspect'")

    return df

# This function takes in the string label of aspect, and the training data and creates a gold BIOES label for the text. 
# The BIOES label is based on the tokenized aspect and training text

def generate_train_data(lang, task, subtask, domain, file_name):
    
    
    # Get Raw Data
    if lang == 'jpn':
        train_url = "https://raw.githubusercontent.com/DimABSA/DimABSA2026/refs/heads/main/task-dataset/track_a/subtask_1/jpn/jpn_hotel_train_alltasks.jsonl"
    
    else: 
        train_url = f"https://raw.githubusercontent.com/DimABSA/DimABSA2026/refs/heads/main/task-dataset/track_a/{subtask}/{lang}/{lang}_{domain}_train_alltasks.jsonl"
    
    # Transform data to DF
    train_raw = load_jsonl_url(train_url)
    train_df = jsonl_to_df(train_raw)

    print(train_df)



    # Adding BIOES label column
    # train_df = train_df.reset_index(drop=True)
    # train_df["BIOES"] = None
    
    # with pd.option_context('display.max_columns', None):
    #     print(train_df.head())

    # for x in range(len(train_df)):
    #     labels = []

    #     # Tokenize Data
    #     text = train_df.iloc[x]["Text"]
    #     text_enc = tokenizer(text, truncation=True, padding="max_length", max_length=512,return_tensors="pt")
    #     sentence_enc = text_enc["input_ids"][0]


    #     aspect_term = train_df.iloc[x]["Aspect"]
    #     asp_tokens = tokenizer(aspect_term, truncation = True, max_length = 512, return_tensors="pt")
    #     asp_enc = asp_tokens["input_ids"][0]
    #     asp_enc = asp_enc[1:-1] # removing CLS and SEP tokens

    #     # If language is Chinese, indexes of where the aspect is generated by looping through text tokens and checking against aspect tokens
    #     if lang == 'zho':
    #         asp_len = len(asp_enc)

    #         indices = []
    #         index = 0
    #         asp_index = 0
    #         while index < len(sentence_enc):

    #             if asp_enc[asp_index] == sentence_enc[index]:
    #                 indices.append(index)
    #                 asp_index += 1 

    #                 if asp_index >= asp_len:
    #                     asp_index = 0

    #             index += 1 

    #     # If language is not Chinese, indexes of where the aspect is generated by creating a mask, then looping through data, checking against the mask. 
    #     else:    
    #         mask = torch.zeros_like(sentence_enc, dtype=torch.bool)
    #         asp_len = len(asp_enc)
    #         for i in range(len(sentence_enc) - asp_len + 1):
    #             if torch.all(sentence_enc[i:i+asp_len] == asp_enc):
    #                 mask[i:i+asp_len] = True
    #         indices = torch.where(mask)[0]
        
    #     # This is a check for duplicates. The apesct term can appear multiple times in the training sentence. For the purposes of task 1, we only need the 
    #     # single aspect term
    #     if len(indices) >= asp_len:
    #         non_dupulicate_indices = []
    #         for i_pointer in range(0, asp_len):
    #             non_dupulicate_indices.append(i_pointer)
            
    #         indices = [indices[i] for i in non_dupulicate_indices]

    #     # If the aspect term is null, label all text tokens as outside, and padding tokens Pad
    #     if len(indices) == 0:
    #         for ind in range(len(sentence_enc)):
    #             if sentence_enc[ind] != 0:
    #                 labels.append(ASP_O)
    #             else: 
    #                 labels.append(ASP_P)

    #     # The labels are generated by checking the index list for postions in the tokenized text that match the aspect. 
    #     # Lookahead and lookbehind checks are done to determine the Beggining, inside, and end aspect labels.
    #     else:
    #         for ind in range(len(sentence_enc)):
    #             if ind not in indices:
    #                 if sentence_enc[ind] != 0 and (sentence_enc[ind] != 101) and (sentence_enc[ind] != 101):
    #                     labels.append(ASP_O)
    #                 else: 
    #                     labels.append(ASP_P)
    #             elif ind in indices:
    #                 if ind == 0:
    #                     if (ind + 1) in indices:
    #                         labels.append(ASP_B)
    #                     else:
    #                         labels.append(ASP_S)
    #                 elif ind == len(sentence_enc) - 1:
    #                     if (ind - 1) in indices:
    #                         labels.append(ASP_E)
    #                     else:
    #                         labels.append(ASP_S)
    #                 elif ((ind - 1) in indices) and ((ind + 1) in indices):
    #                     labels.append(ASP_I)
    #                 elif ((ind - 1) in indices):
    #                     labels.append(ASP_E)
    #                 elif ((ind + 1) in indices):
    #                     labels.append(ASP_B)
    #                 else:
    #                     labels.append(ASP_S)
                
    #     train_df.at[x, "BIOES"] = labels
    train_df.to_json(file_name, orient="records", lines=True)


        

        


def main(): 
    subtask = "subtask_1"#don't change
    task = "task1"#don't change
    lang = "eng" #chang the language you want to test
    domain = "laptop" #change what domain you want to test
    tokenizer = "distilbert-base-multilingual-cased"
    f_name = "subtask_1_eng_laptop.json"

    generate_train_data(lang, task, subtask, domain, tokenizer, "bioes", f_name)

    # aug_df_bioes_lab = pd.read_json("subtask_a_eng_laptop.json", orient="records", lines=True)

    # test_labeling(aug_df_bioes_lab, tokenizer, lang, domain)


if __name__ == "__main__":
    main()

